<?php

namespace Database\Seeders;

use App\Models\CorpoCeleste;
use Illuminate\Database\Seeder;

class CorpoCelesteSeeder extends Seeder
{
    public function run(): void
    {
        $categoriaNomi = [
            1 => 'Pianeta',
            2 => 'Stella',
            3 => 'Luna',
            4 => 'Galassia',
            5 => 'Nebulosa',
            6 => 'Asteroide',
            7 => 'Cometa',
            8 => 'Pianeta Nano',
        ];

        $catLookup = \App\Models\Categoria::pluck('id', 'nome');

        $corpi = [
            // Stelle (categoria_id = 2)
            [
                'nome' => 'Sole',
                'categoria_id' => 2,
                'immagine' => 'sole.jpg',
                'descrizione' => 'Il Sole è la stella madre del sistema solare, una sfera di plasma con un diametro di circa 1.4 milioni di chilometri. La sua energia è il motore di tutta la vita sulla Terra.',
                'tipo' => 'Stella nana gialla',
                'massa_kg' => '1.989e30',
                'distanza_km' => '0',
                'diametro_km' => 1392700,
                'gravita' => 274.0,
                'temperatura' => 5500,
                'periodo_orbitale' => null,
                'scopritore' => null,
                'anno_scoperta' => null,
                'in_evidenza' => true,
            ],
            // Pianeti (categoria_id = 1)
            [
                'nome' => 'Mercurio',
                'categoria_id' => 1,
                'immagine' => 'mercurio.jpg',
                'descrizione' => 'Mercurio è il pianeta più piccolo e più vicino al Sole. La sua superficie è craterizzata e simile alla Luna, senza atmosfera significativa.',
                'tipo' => 'Pianeta roccioso',
                'massa_kg' => '3.301e23',
                'distanza_km' => '57900000',
                'diametro_km' => '4879.4',
                'gravita' => 3.7,
                'temperatura' => 167,
                'periodo_orbitale' => 87.97,
                'scopritore' => null,
                'anno_scoperta' => null,
                'in_evidenza' => false,
            ],
            [
                'nome' => 'Venere',
                'categoria_id' => 1,
                'immagine' => 'venere.jpg',
                'descrizione' => 'Venere è il pianeta più caldo del sistema solare a causa del suo spesso strato di nubi che intrappolano il calore. Ruota in senso opposto rispetto agli altri pianeti.',
                'tipo' => 'Pianeta roccioso',
                'massa_kg' => '4.867e24',
                'distanza_km' => '108200000',
                'diametro_km' => '12104',
                'gravita' => 8.87,
                'temperatura' => 462,
                'periodo_orbitale' => 224.7,
                'scopritore' => null,
                'anno_scoperta' => null,
                'in_evidenza' => false,
            ],
            [
                'nome' => 'Terra',
                'categoria_id' => 1,
                'immagine' => 'terra.jpg',
                'descrizione' => 'La Terra è il terzo pianeta in ordine di distanza dal Sole e l\'unico noto ad ospitare la vita. Il 71% della sua superficie è coperta da acqua.',
                'tipo' => 'Pianeta roccioso',
                'massa_kg' => '5.972e24',
                'distanza_km' => '149600000',
                'diametro_km' => '12756',
                'gravita' => 9.81,
                'temperatura' => 15,
                'periodo_orbitale' => 365.25,
                'scopritore' => null,
                'anno_scoperta' => null,
                'in_evidenza' => true,
            ],
            [
                'nome' => 'Marte',
                'categoria_id' => 1,
                'immagine' => 'marte.jpg',
                'descrizione' => 'Marte è il quarto pianeta del sistema solare, noto come il "pianeta rosso" per il suo colore dovuto all\'ossido di ferro sulla superficie.',
                'tipo' => 'Pianeta roccioso',
                'massa_kg' => '6.417e23',
                'distanza_km' => '227900000',
                'diametro_km' => '6792.4',
                'gravita' => 3.72,
                'temperatura' => -65,
                'periodo_orbitale' => 687,
                'scopritore' => null,
                'anno_scoperta' => null,
                'in_evidenza' => true,
            ],
            [
                'nome' => 'Giove',
                'categoria_id' => 1,
                'immagine' => 'giove.jpg',
                'descrizione' => 'Giove è il pianeta più grande del sistema solare, una gigante gassosa con una massa pari a 2.5 volte quella di tutti gli altri pianeti messi insieme.',
                'tipo' => 'Gigante gassoso',
                'massa_kg' => '1.898e27',
                'distanza_km' => '778500000',
                'diametro_km' => '142984',
                'gravita' => 24.79,
                'temperatura' => -110,
                'periodo_orbitale' => 4332.59,
                'scopritore' => null,
                'anno_scoperta' => null,
                'in_evidenza' => true,
            ],
            [
                'nome' => 'Saturno',
                'categoria_id' => 1,
                'immagine' => 'saturno.jpg',
                'descrizione' => 'Saturno è il sesto pianeta del sistema solare, famoso per il suo spettacolare sistema di anelli composti principalmente da ghiaccio e polvere.',
                'tipo' => 'Gigante gassoso',
                'massa_kg' => '5.683e26',
                'distanza_km' => '1432000000',
                'diametro_km' => '120536',
                'gravita' => 10.44,
                'temperatura' => -140,
                'periodo_orbitale' => 10759.22,
                'scopritore' => null,
                'anno_scoperta' => null,
                'in_evidenza' => true,
            ],
            [
                'nome' => 'Urano',
                'categoria_id' => 1,
                'immagine' => 'urano.jpg',
                'descrizione' => 'Urano è il settimo pianeta del sistema solare, un gigante di ghiaccio con un caratteristico colore azzurro-verde dovuto al metano nella sua atmosfera.',
                'tipo' => 'Gigante di ghiaccio',
                'massa_kg' => '8.681e25',
                'distanza_km' => '2871000000',
                'diametro_km' => '51118',
                'gravita' => 8.87,
                'temperatura' => -195,
                'periodo_orbitale' => 30688.5,
                'scopritore' => 'William Herschel',
                'anno_scoperta' => 1781,
                'in_evidenza' => false,
            ],
            [
                'nome' => 'Nettuno',
                'categoria_id' => 1,
                'immagine' => 'nettuno.jpg',
                'descrizione' => 'Nettuno è l\'ottavo e più lontano pianeta del sistema solare. È un mondo blu e freddo con i venti più veloci del sistema solare, che raggiungono i 2100 km/h.',
                'tipo' => 'Gigante di ghiaccio',
                'massa_kg' => '1.024e26',
                'distanza_km' => '4495000000',
                'diametro_km' => '49528',
                'gravita' => 11.15,
                'temperatura' => -200,
                'periodo_orbitale' => 60182,
                'scopritore' => 'Johann Galle',
                'anno_scoperta' => 1846,
                'in_evidenza' => false,
            ],
            // Lune (categoria_id = 3)
            [
                'nome' => 'Luna',
                'categoria_id' => 3,
                'immagine' => 'luna.jpg',
                'descrizione' => 'La Luna è l\'unico satellite naturale della Terra e il quinto più grande del sistema solare. È l\'unico corpo celeste oltre la Terra ad essere stato visitato dall\'uomo.',
                'tipo' => 'Satellite naturale',
                'massa_kg' => '7.342e22',
                'distanza_km' => '384400',
                'diametro_km' => '3474.8',
                'gravita' => 1.62,
                'temperatura' => -20,
                'periodo_orbitale' => 27.32,
                'scopritore' => null,
                'anno_scoperta' => null,
                'in_evidenza' => true,
            ],
            [
                'nome' => 'Europa',
                'categoria_id' => 3,
                'immagine' => 'europa.jpg',
                'descrizione' => 'Europa è una delle lune di Giove, coperta da una crosta di ghiaccio d\'acqua che nasconde un oceano liquido, rendendola uno dei candidati più promettenti per la vita extraterrestre.',
                'tipo' => 'Satellite ghiacciato',
                'massa_kg' => '4.799e22',
                'distanza_km' => '628300000',
                'diametro_km' => '3121.6',
                'gravita' => 1.31,
                'temperatura' => -160,
                'periodo_orbitale' => 3.55,
                'scopritore' => 'Galileo Galilei',
                'anno_scoperta' => 1610,
                'in_evidenza' => false,
            ],
            [
                'nome' => 'Titano',
                'categoria_id' => 3,
                'immagine' => 'titano.jpg',
                'descrizione' => 'Titano è la più grande luna di Saturno, con una spessa atmosfera ricca di azoto e laghi di metano liquido sulla superficie.',
                'tipo' => 'Satellite atmosferico',
                'massa_kg' => '1.345e23',
                'distanza_km' => '1221870000',
                'diametro_km' => '5150',
                'gravita' => 1.35,
                'temperatura' => -179,
                'periodo_orbitale' => 15.95,
                'scopritore' => 'Christiaan Huygens',
                'anno_scoperta' => 1655,
                'in_evidenza' => false,
            ],
            // Galassie (categoria_id = 4)
            [
                'nome' => 'Andromeda',
                'categoria_id' => 4,
                'immagine' => 'andromeda.jpg',
                'descrizione' => 'La Galassia di Andromeda è la galassia a spirale più vicina alla Via Lattea. È in rotta di collisione con la nostra galassia tra circa 4.5 miliardi di anni.',
                'tipo' => 'Galassia a spirale',
                'massa_kg' => '2.5e42',
                'distanza_km' => '2.365e19',
                'diametro_km' => '1.9e18',
                'gravita' => null,
                'temperatura' => null,
                'periodo_orbitale' => null,
                'scopritore' => 'Abd al-Rahman al-Sufi',
                'anno_scoperta' => 964,
                'in_evidenza' => true,
            ],
            [
                'nome' => 'Via Lattea',
                'categoria_id' => 4,
                'immagine' => 'via-lattea.jpg',
                'descrizione' => 'La Via Lattea è la galassia che ospita il sistema solare. Contiene oltre 100 miliardi di stelle ed ha un diametro di circa 100.000 anni luce.',
                'tipo' => 'Galassia a spirale barrata',
                'massa_kg' => '3.0e42',
                'distanza_km' => '0',
                'diametro_km' => '9.46e17',
                'gravita' => null,
                'temperatura' => null,
                'periodo_orbitale' => null,
                'scopritore' => null,
                'anno_scoperta' => null,
                'in_evidenza' => true,
            ],
            // Nebulose (categoria_id = 5)
            [
                'nome' => 'Nebulosa di Orione',
                'categoria_id' => 5,
                'immagine' => 'orione.jpg',
                'descrizione' => 'La Nebulosa di Orione è una delle nebulose più luminose del cielo, visibile anche a occhio nudo. È un vivaio stellare dove nascono nuove stelle.',
                'tipo' => 'Nebulosa a emissione',
                'massa_kg' => '2.0e30',
                'distanza_km' => '1.307e16',
                'diametro_km' => '2.37e14',
                'gravita' => null,
                'temperatura' => null,
                'periodo_orbitale' => null,
                'scopritore' => 'Nicolas-Claude Fabri de Peiresc',
                'anno_scoperta' => 1610,
                'in_evidenza' => true,
            ],
            // Asteroidi (categoria_id = 6)
            [
                'nome' => 'Cerere',
                'categoria_id' => 6,
                'immagine' => 'cerere.jpg',
                'descrizione' => 'Cerere è il più grande asteroide della fascia principale tra Marte e Giove. È abbastanza grande da essere considerato un pianeta nano.',
                'tipo' => 'Asteroide',
                'massa_kg' => '9.393e20',
                'distanza_km' => '413700000',
                'diametro_km' => '939.4',
                'gravita' => 0.28,
                'temperatura' => -105,
                'periodo_orbitale' => 1681.6,
                'scopritore' => 'Giuseppe Piazzi',
                'anno_scoperta' => 1801,
                'in_evidenza' => false,
            ],
            // Comete (categoria_id = 7)
            [
                'nome' => 'Cometa di Halley',
                'categoria_id' => 7,
                'immagine' => 'halley.jpg',
                'descrizione' => 'La Cometa di Halley è la più famosa cometa periodica, visibile dalla Terra ogni 75-76 anni. Il suo nucleo è composto da ghiaccio e polvere.',
                'tipo' => 'Cometa periodica',
                'massa_kg' => '2.2e14',
                'distanza_km' => '7560000000',
                'diametro_km' => '11',
                'gravita' => null,
                'temperatura' => null,
                'periodo_orbitale' => 75.3,
                'scopritore' => null,
                'anno_scoperta' => null,
                'in_evidenza' => false,
            ],
            // Pianeti nani (categoria_id = 8)
            [
                'nome' => 'Plutone',
                'categoria_id' => 8,
                'immagine' => 'plutone.jpg',
                'descrizione' => 'Plutone è stato a lungo considerato il nono pianeta del sistema solare prima di essere riclassificato come pianeta nano nel 2006. Ha un cuore di ghiaccio sulla superficie.',
                'tipo' => 'Pianeta nano',
                'massa_kg' => '1.309e22',
                'distanza_km' => '5906000000',
                'diametro_km' => '2376.6',
                'gravita' => 0.62,
                'temperatura' => -230,
                'periodo_orbitale' => 90560,
                'scopritore' => 'Clyde Tombaugh',
                'anno_scoperta' => 1930,
                'in_evidenza' => true,
            ],
        ];

        foreach ($corpi as $data) {
            $data['categoria_id'] = $catLookup[$categoriaNomi[$data['categoria_id']]] ?? $data['categoria_id'];
            CorpoCeleste::create($data);
        }
    }
}
